sudo: false

language: python

python:
  - "3.4"
  - "3.5"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - pip install -r test_requirements.txt
  - pip install openpnm
  - chmod a+x run_tests

script:
  - python run_tests

notifications:
  email: false
